language: node_js
node_js: 
  - "stable"
env:
  global:
    - CC_TEST_REPORTER_ID=d110037bf443549bed5413ba7b80bf5f00157117c96ce5b53657a4654977c660
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coveralls
  - npm run coverage
  - npm run report
notification:
  email: false
services:
- postgresql
env:
- DB_USERNAME=postgres DB_PASSWORD=08165842442 DBNAME=politico
before_script:
- psql -c 'create database politico_test;' -U postgres
- psql -c "CREATE USER postgres WITH PASSWORD '08165842442';" -U postgres
